apiVersion: v1
kind: Elasticsearch
metadata:
  name: my-elasticsearch
  namespace: efk
spec:
  version: 7.12.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
