apiVersion: v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.12.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://my-elasticsearch.efk.svc.cluster.local:9200" # Change to your Elasticsearch service DNS
          ports:
            - containerPort: 5601
